Fix build for clang-r563880
Code fails to build with clang-r563880 with the following error:
  error: static_cast from 'const std::string *' to 'void *' is not allowed

https://llvm.org/pr110355 implemented LWG3870, and no longer performs
voidify. Explicitly perform const_cast to resolve the issue.

Test: presubmit
Bug: 405860747
Flag: EXEMPT code cleanup
Change-Id: I2ee5db1f4162050cf27ed32333083c67f31812d3