Fix implicit integer conversion between int and uint8_t
We add static_cast so it has an explict cast for integer
conversion.

frameworks/native/services/surfaceflinger/Display/DisplayIdentification.cpp:464:70:
error: implicit conversion loses integer precision: 'int' to 'const
uint8_t' (aka 'const unsigned char') [-Werror,-Wimplicit-int-conversion]
  464 |     const uint8_t lowByte = static_cast<uint8_t>(id.value) ==
port ? ~port : port;
      |                   ~~~~~~~
^~~~~
1 error generated.

Flag: EXEMPT warning flag bugfix
Bug: 430598176
Test: m && presubmits
Change-Id: Id66cada4933a6ce68e903b8dbdace6e929b9766d